import React, { useState, useMemo } from 'react';
import { GoogleGenAI, Type } from '@google/genai';
import { useAppContext } from './AppContext';
import { ArrowLeftIcon, BottomNavbar, Modal } from './components';
import { styles } from './styles';
import { MovieNightEvent, MovieSuggestion } from './types';

// --- MODALS ---
const AddMovieModal = ({ onClose, onSave, isLoading }: { onClose: () => void; onSave: (title: string) => void; isLoading: boolean; }) => {
    const [title, setTitle] = useState('');
    return (
        <Modal onClose={onClose} title="Suggest a Movie">
            <div style={styles.formGroup}>
                <label style={styles.label} htmlFor="movie-title">Movie Title</label>
                <input id="movie-title" style={styles.input} value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g., The Matrix" />
                <small style={{ color: '#7f8c8d', marginTop: '5px', display: 'block' }}>The movie summary will be generated by AI.</small>
            </div>
            <div style={styles.formActions}>
                <button onClick={onClose} style={{ ...styles.button, ...styles.buttonSecondary }}>Cancel</button>
                <button onClick={() => onSave(title)} style={styles.button} disabled={isLoading || !title}>
                    {isLoading ? '🧠 Thinking...' : 'Add Suggestion'}
                </button>
            </div>
        </Modal>
    );
};

// --- MAIN VIEW ---
const MovieNightView = () => {
    const { onNavigate, personalizationData, onSavePersonalization, profiles, currentViewingProfile, addToast } = useAppContext();
    const isParentView = currentViewingProfile.role === 'Admin' || currentViewingProfile.role === 'Parent';

    const allEvents = useMemo(() => (personalizationData.movieNightEvents || []), [personalizationData.movieNightEvents]);
    const allSuggestions = useMemo(() => (personalizationData.movieSuggestions || []), [personalizationData.movieSuggestions]);

    const [isAddModalOpen, setAddModalOpen] = useState(false);
    const [isLoading, setIsLoading] = useState(false);

    // Find the most recent event that's still in the 'voting' phase
    const currentEvent = useMemo(() => {
        return [...allEvents]
            .filter(e => e.status === 'voting')
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
    }, [allEvents]);

    const eventSuggestions = useMemo(() => {
        if (!currentEvent) return [];
        return allSuggestions
            .filter(s => s.eventId === currentEvent.id)
            .sort((a, b) => b.votes.length - a.votes.length);
    }, [allSuggestions, currentEvent]);

    const getProfileName = (id: string) => {
        if (id === 'ai_assistant') return '🤖 AI Assistant';
        return profiles.find(p => p.id === id)?.name || 'Unknown';
    };

    const handleVote = (suggestionId: string) => {
        if (!currentEvent || currentEvent.status === 'closed') return;
        
        const updatedSuggestions = allSuggestions.map(s => {
            if (s.eventId !== currentEvent.id) return s; // Don't touch other events' suggestions

            // Remove current user's vote from any suggestion in this event
            const votes = s.votes.filter(voterId => voterId !== currentViewingProfile.id);
            
            // Add vote to the selected suggestion
            if (s.id === suggestionId) {
                return { ...s, votes: [...votes, currentViewingProfile.id] };
            }
            return { ...s, votes };
        });

        onSavePersonalization({ movieSuggestions: updatedSuggestions });
        addToast("Your vote has been cast!", 'badge');
    };

    const handleAddSuggestion = async (title: string) => {
        if (!title.trim() || !currentEvent || !process.env.API_KEY) return;
        setIsLoading(true);

        try {
            const ai = new GoogleGenAI({apiKey: process.env.API_KEY});
            const prompt = `Give me a one-sentence summary for the movie "${title}". Respond with just the summary text, no extra words or labels.`;
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
            });
            const summary = response.text.trim();

            const newSuggestion: MovieSuggestion = {
                id: `sugg_${Date.now()}`,
                eventId: currentEvent.id,
                title: title.trim(),
                description: summary,
                posterUrl: `https://placehold.co/400x600/34495e/ffffff?text=${encodeURIComponent(title.trim())}`,
                suggestedBy: currentViewingProfile.id,
                votes: [currentViewingProfile.id], // suggester automatically votes
            };

            onSavePersonalization({ movieSuggestions: [...allSuggestions, newSuggestion] });
            addToast("Movie suggested!", 'badge');
            setAddModalOpen(false);

        } catch (error) {
            console.error("Error adding suggestion:", error);
            addToast("Couldn't add suggestion. Please try again.", 'info');
        } finally {
            setIsLoading(false);
        }
    };
    
    const handleAiSuggestions = async () => {
        if (!currentEvent || !process.env.API_KEY) return;
        setIsLoading(true);
        try {
            const ai = new GoogleGenAI({apiKey: process.env.API_KEY});
            const familyProfile = profiles.map(p => `${p.role} (age ${p.age || 'N/A'})`).join(', ');
            const prompt = `Suggest 3 family-friendly movies for a family with: ${familyProfile}. Do not suggest movies that are already in this list: ${eventSuggestions.map(s=>s.title).join(', ')}. For each movie, provide the title and a one-sentence summary.`;

            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
                config: {
                    responseMimeType: 'application/json',
                    responseSchema: {
                        type: Type.OBJECT,
                        properties: {
                            suggestions: {
                                type: Type.ARRAY,
                                items: {
                                    type: Type.OBJECT,
                                    properties: {
                                        title: { type: Type.STRING },
                                        summary: { type: Type.STRING },
                                    }
                                }
                            }
                        }
                    }
                }
            });

            const aiData = JSON.parse(response.text);
            const newSuggestions: MovieSuggestion[] = aiData.suggestions.map((item: any) => ({
                 id: `sugg_${Date.now()}_${item.title.replace(/\s/g, '')}`,
                eventId: currentEvent.id,
                title: item.title,
                description: item.summary,
                posterUrl: `https://placehold.co/400x600/9b59b6/ffffff?text=${encodeURIComponent(item.title)}`,
                suggestedBy: 'ai_assistant',
                votes: [],
            }));

            onSavePersonalization({ movieSuggestions: [...allSuggestions, ...newSuggestions] });
            addToast("AI suggestions added!", 'badge');

        } catch (error) {
            console.error("AI suggestion failed:", error);
            addToast("AI failed to generate suggestions.", 'info');
        } finally {
            setIsLoading(false);
        }
    };

    const handleCloseVoting = () => {
        if (!currentEvent) return;
        const winner = eventSuggestions[0]; // Assumes suggestions are sorted by vote count
        const updatedEvents = allEvents.map(e => e.id === currentEvent.id ? { ...e, status: 'closed' as 'closed', winnerMovieId: winner?.id || undefined } : e);
        onSavePersonalization({ movieNightEvents: updatedEvents });
        addToast(`Voting closed! The winner is "${winner.title}"`, 'badge');
    };
    
    const handleCreateEvent = () => {
         const nextFriday = new Date();
         nextFriday.setDate(nextFriday.getDate() + (5 + 7 - nextFriday.getDay()) % 7);
         const newEvent: MovieNightEvent = {
            id: `mne_${Date.now()}`,
            date: nextFriday.toISOString().split('T')[0],
            status: 'voting'
         };
         onSavePersonalization({movieNightEvents: [...allEvents, newEvent]});
         addToast("New Movie Night event created!", 'badge');
    }

    const renderCard = (s: MovieSuggestion) => {
        const hasVoted = s.votes.includes(currentViewingProfile.id);
        const isWinner = currentEvent?.status === 'closed' && currentEvent.winnerMovieId === s.id;
        const cardStyle = { ...styles.suggestionCard, ...(isWinner ? styles.winnerCard : {}) };
        
        return (
            <div key={s.id} style={cardStyle}>
                 {isWinner && <div style={styles.winnerBanner}>Winner!</div>}
                <img src={s.posterUrl} alt={s.title} style={styles.suggestionPoster} />
                <div style={styles.suggestionBody}>
                    <h3 style={styles.suggestionTitle}>{s.title}</h3>
                    <p style={styles.suggestionDesc}>{s.description}</p>
                    <p style={styles.suggestedBy}>Suggested by: {getProfileName(s.suggestedBy)}</p>
                    <div style={styles.voteInfo}>
                        <span style={styles.voteCount}>
                            {s.votes.length} {s.votes.length === 1 ? 'Vote' : 'Votes'}
                        </span>
                        <button
                            onClick={() => handleVote(s.id)}
                            style={{ ...styles.button, ...styles.voteButton, ...(hasVoted ? styles.votedButton : {}) }}
                            disabled={currentEvent?.status === 'closed'}
                        >
                            {hasVoted ? 'Voted ✔' : 'Vote'}
                        </button>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div style={styles.pageContainer}>
            <header style={styles.header}>
                <button style={{ ...styles.navButton, flexShrink: 0, width: 40 }} onClick={() => onNavigate('dashboard')}>
                    <ArrowLeftIcon />
                </button>
                <h2 style={styles.pageHeader}>🎬 Movie Night</h2>
                <div style={{ flexShrink: 0, width: 40 }}></div>
            </header>
            <main style={styles.mainContent}>
                {currentEvent ? (
                    <>
                        <section style={styles.section}>
                            <h2 style={{ textAlign: 'center', marginBottom: '20px' }}>
                                Voting for {new Date(currentEvent.date + 'T00:00:00').toLocaleDateString('en-us', { weekday: 'long', month: 'long', day: 'numeric' })}
                            </h2>
                            <div style={styles.actionsContainer}>
                                <button style={{...styles.button, flexGrow: 1}} onClick={() => setAddModalOpen(true)} disabled={currentEvent.status === 'closed'}>+ Add Suggestion</button>
                                <button style={{...styles.button, ...styles.buttonSecondary, flexGrow: 1}} onClick={handleAiSuggestions} disabled={isLoading || currentEvent.status === 'closed'}>
                                    {isLoading ? '🧠...' : '✨ Get AI Ideas'}
                                </button>
                                {isParentView && currentEvent.status === 'voting' && (
                                    <button style={{...styles.button, ...styles.buttonSuccess, width: '100%'}} onClick={handleCloseVoting}>🏆 Close Voting & See Winner</button>
                                )}
                            </div>
                        </section>
                        <div style={styles.suggestionGrid}>
                            {eventSuggestions.map(renderCard)}
                        </div>
                    </>
                ) : (
                    <div style={styles.section}>
                        <h3 style={{textAlign: 'center'}}>No Active Movie Night</h3>
                        <p style={{textAlign: 'center', margin: '15px 0'}}>There are no movie nights currently being planned.</p>
                        {isParentView && (
                             <button style={{...styles.button, width: '100%'}} onClick={handleCreateEvent}>+ Start a New Movie Night Poll</button>
                        )}
                    </div>
                )}
            </main>
            
            {isAddModalOpen && (
                <AddMovieModal 
                    onClose={() => setAddModalOpen(false)}
                    onSave={handleAddSuggestion}
                    isLoading={isLoading}
                />
            )}
            
            <BottomNavbar activePage="movieNightPicker" onNavigate={onNavigate} />
        </div>
    );
};

export default MovieNightView;